language: R
sudo: false
cache: packages

# script: true # use to recach travis packages -- https://steinbaugh.com/posts/travis-cache.html

addons:
  apt:
    update: true

before_install:
  - sudo apt-get -y install libgit2-dev

r_packages:
  - usethis
  - covr
  - devtools
  - roxygen2
  - BiocManager

bioc_required: true

bioc_check: true

r:
  - bioc-release
  - bioc-devel

warnings_are_errors: false

after_success:
- Rscript -e 'library(covr);codecov(quiet = FALSE)'

env: _R_CHECK_CRAN_INCOMING_=FALSE

deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  api_key:
    secure: adpUK/mFdr/+QGv3SMjvSK/91bCO7eOvPStwx75waotNtjmKyEkP4yWfNhWvqThreLFgt6j2tojsdgZ93U40EwO63hyi9aSnD/Pbe6frUQszNv7R2WJt17dGBFtSGhXyZkWDikjWobVL28S1rWqz+/PbAJKg//QUxAkLU/KO0ZAXEcQy4DJ/SLl0dT6h0qAjpvuUWGruVb6AhVlJt+re0Lo7zxsaoSTelvICdcAb2C/djuShtjMzRQWSLSpuyyabmazqASaHw4yddGfCkWu3JYRWJsGMi3GWcrxiz0ldt64PnvBXcT5zyxqDja9rHiXTitRjGgZimejQFg3vwhnVG+lE3Vz8opb7j+Y2FiH0iGEUB7SM8Jg+63JCpLus+jrB4j3HnR8BEOWmFBeKpSGOEhIGB+RQ0e+j+qg+0sQSqm/cTHYudU6gMNImLIY/8MjD4D1DjXD/Q2emMlEMF2y0wvCib48wIUaVoh8zipb764kdOLxBO/pWAa80pM82xiFXp+p+BsA/uaDh6fEv2y062Xb/Py1eKl1MadkngFM3EW6JwC4TUFGuGeRBPSVAAOMGXp/BpTHe1EC7ZB7gYxmhO05LPjicjrSqFYUksL8cQBQ2izF63QKA67zFT8zFL56qXzWIgErEy044pKg1Z25+8tCnUj3ec8uwZfopw8sdgEY=
  file_glob: true
  file: "glmSparseNet*.tar.gz"
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME = linux && $TRAVIS_R_VERSION_STRING = 'bioc-release'"
